### ISSUE TITLE
Monitor chromecast for media playback (from any receiver?)

### ISSUE THREAD

**Issue by ipeters** [thibauts/node-castv2-client#18]
I have a raspberry pi that is capable of asserting/removing a 12v trigger signal connected to my home stereo equipment. In the past I have successfully had it monitoring my Sonos Connect device, allowing it to turn on the external amp when the Sonos begins playback, and turn off the external amp shortly after the Sonos stops playback.

I'm hoping to achieve the same thing with a Chromecast (being used exclusively for audio, via an HDMI->toslink separator). Basically, I need to have something running on the rpi that can detect when there's something running on the Chromecast, and when it's idle.

In a perfect world, it would be able to reliably sense whether the current app on the Chromecast -- receiver, if I understand correctly -- is actively playing music / making noise, but I'm not sure if there's a reliable and general way to do that.

Probably sufficient is to just detect whether anything is running on the Chromecast at all, or if it has reverted to its default state, and toggle the trigger signal then.

Does this sound like something that's possible to achieve at all with Chromecast? And, if so, am I looking in the right place? Most documentation of various projects seems (understandably) to be focused on writing a custom receiver and interacting with it, while I'm just trying to monitor the Chromecast / watch for broadcast messages about its state.

Thanks for any help or thoughts you have!

**Comment by thibauts** [comment]
You'll be able to monitor when apps are launched or stopped with this : 

```javascript
client.on('status', function(status) {
  console.log(status);
});
```

When an app implementing the `urn:x-cast:com.google.cast.media` protocol is launched (the implemented protocols are in the status message logged above) you'll have to join the app session and monitor its status updates on the media protocol channel. These status updates are implemented in the `DefaultMediaReceiver` as `status` events. This would go something like this :

```javascript
client.getSessions(function(err, sessions) {
   var session = sessions[0]; // For now only one app runs at once, so using the first session should be ok
   client.join(session, DefaultMediaReceiver, function(err, app) {
      app.on('status', function(status) {
         console.log(status);
      });
   });
});
```

Here I'm using the `DefaultMediaReceiver` as it can be used as a generic app to control media playback, as long as the target app uses the standard media protocol.

This code above is totally untested but I'm quite confident you'll be able to achieve what you want by doing something along these lines.

Let me know if you encounter problems or bugs, I'll try to help you.

**Comment by ipeters** [comment]
Thanks so much for your help. I'm sorry I was so slow in responding, but with your examples I was able to get things working.

**Comment by DrSurround** [comment]
@ipeters this is a great solution and something I've been searching for recently.  I would like to get the same system working for my amplifiers attached to Chromecast Audio devices at home.  Would you be willing to share your example code / modifications in a repository?

**Comment by ipeters** [comment]
@DrSurround absolutely. I'll pull what I've got off my rpi, clean it up a tad and put it up soon as I can.

**Comment by thibauts** [comment]
Indeed this would probably be very useful to many Chromecast (audio) owners ...

I can easily see how this could be extracted as a module that connects to a Chromecast and emits events when the device starts / stops media apps.

If you need any help with this I'll be happy to help

**Comment by DrSurround** [comment]
Thank you both, I look foward to seeing what can come together. I know I'm not alone in searching for a solution! :+1:

**Comment by tbharthur** [comment]
hi @ipeters and @thibauts  -- is this something you guys were ever able to get working?  I'm looking to do something nearly identical to what @DrSurround is shooting for.  would love to be able to trigger a harmony activity when i start streaming to a connected Chromecast Audio...

**Comment by netconstructor** [comment]
Bump -

Would be very interested if anyone was able to get this operational
