### ISSUE TITLE
Bypass the user interaction need

### ISSUE THREAD

**Issue by kriptolix** [thibauts/node-castv2-client#20]
How did you bypass the user interaction need to establish a session with chromecast? I am trying to understand how  do this in my own chromecast sender.

**Comment by thibauts** [comment]
What interaction are you talking about?
Le 16 janv. 2015 15:47, "Diego C sampaio" <notifications@github.com> a
écrit :

**Comment by kriptolix** [comment]
Ok, that's a wrong question, sorry. When I asked I was trying to stream videos by chromecast extension, only after I see that castv2-client don't need this. Sorry again and congratulations, your docs about v2 protocol was very much useful to understand the new lines to stream to a chromecast.

**Comment by thibauts** [comment]
No problem, you're welcome !
