### ISSUE TITLE
Unhandled timeout error

### ISSUE THREAD

**Issue by RIAEvangelist** [thibauts/node-castv2-client#21]
I get a few errors while running normally causing a crash.

I can reproduce every time if I power off the chromecast by unplugging it.

I am getting an error through the client on('error' event.

Any ideas as to if this is more likely me or the lib?

Any suggestions on how to handle this properly?

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Device timeout
    at HeartbeatController.ontimeout (/home/bmiller/git/nwjs-cast/node_modules/castv2-client/lib/senders/platform.js:56:26)
    at HeartbeatController.g (events.js:180:16)
    at HeartbeatController.emit (events.js:92:17)
    at ontimeout [as _onTimeout] (/home/bmiller/git/nwjs-cast/node_modules/castv2-client/lib/controllers/heartbeat.js:46:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by RIAEvangelist** [comment]
its actually coming from platform.js
line 56

      self.heartbeat.once('timeout', ontimeout);

    function ontimeout() {
      self.emit('error', new Error('Device timeout'));
    });

**Comment by RIAEvangelist** [comment]
The issue was that I was passing the err through in my class.

Please Close

**Comment by thibauts** [comment]
No problem. In case others look, the timeout error actually is the mean to detect device disconnections. You just have to catch it and handle it at the client level with something like

```javascript
client.on('error', function(err) {
  console.log(err.message);
  // handle the error
});
```

If the need arises it will be trial to add error codes to help identify the various possible errors programmatically.
