### ISSUE TITLE
mDNS no longer working?

### ISSUE THREAD

**Issue by queequac** [thibauts/node-castv2-client#22]
From yesterday on my Chromecast does no longer reply to any mDNS query. I have restarted it, plugged it off for a while, etc., but it is no longer discoverable this way.

The official Chromecast app and Youtube on Android still see it, the UPnP based DIAL Service is also still present and working.

Anybody else experiences this? Was there maybe some change within the device regarding discovery? My firmware version is 26653.

**Comment by xat** [comment]
FYI, there is also a related discussion going on here:
https://github.com/xat/castnow/issues/61

**Comment by xat** [comment]
Though I think this issue does not have todo directly with node-castv2-client (since mDNS is not part of it).

**Comment by queequac** [comment]
Yeah, I was quite confident that it was mit related to this client, since I could not find the mdns service via other tools either. But thanks for confirming. Seems I have to add DIAL to my project just for finding the device... Crap

**Comment by xat** [comment]
@queequac 
Did you also try it with https://github.com/xat/chromecast-player ?

**Comment by thibauts** [comment]
I can't reproduce the issue but you could try to sniff your local network with wireshark for both cases and see what differs.

If you can isolate the relevant packets and post the cap files here it's even better :)

**Comment by queequac** [comment]
@xat This is very strange... the chromecast-scanner returned only once in 20(!) runs the chromecast device, in any other case the service was undefined. :/ I wonder whats going on there.

**Comment by queequac** [comment]
btw, wireshark has only shown the mdns response in the valid cases. Got a second successfull discovery in the meanwhile... the rate is below <5% for these. :(
Interesting is also that the Android youtube app seems to send a UPnP M-SEARCH in any case...could not see a mdns response there so far...

**Comment by thibauts** [comment]
There may be a bug in the latest chromecast update that doesn't appear
because many client rely on upnp / ssdp.

**Comment by auchenberg** [comment]
I'm seeing similar issues with firmware ``25525`` and ``25652``, where Chromecasts has stopped appearing in [Bonjour browser for mac](http://www.tildesoft.com/).

However the devices still seems to announce itself over SSDP, so maybe chromecast-scanner  could fallback to SSDP?

**Comment by xat** [comment]
does this code find your chromecast device?
```javascript
var Client = require('node-ssdp').Client
var client = new Client();

client.on('response', function (headers, statusCode, rinfo) {
  console.log('chromecast running on address', rinfo.address);
  client._stop();
});

client.search('urn:dial-multiscreen-org:service:dial:1');
```

**Comment by auchenberg** [comment]
Yup, but I had to wrap the search call in a setTimeout to prevent the process from exiting...

``chromecast running on address 192.168.0.15``

**Comment by xat** [comment]
Okay, then I'll just make an (temporary) chromecast-scanner-ssdp module if the problem over at https://github.com/xat/castnow/issues/61 still occurs.

**Comment by auchenberg** [comment]
Add it as an option in ``chromecast-scanner``? Google might add other discoverability protocols in the future, I assume ``chromecast-scanner`` would need to support these too.

**Comment by xat** [comment]
ah, explicit option is a good idea :D

**Comment by iamdriz** [comment]
What's the fix to get node-castv2-client working again then? I'm not following what the solution is from the above comments. Thanks.
