### ISSUE TITLE
Playing local files

### ISSUE THREAD

**Issue by iamdriz** [thibauts/node-castv2-client#23]
Can this play local files?

e.g. `contentId: 'file:///Users/cameron/Video.mp4`

As when I do that I get the error Load failed here:

~~~
      player.load(media, { autoplay: true }, function(err, status) {
        
        console.log('camstatus', err);

~~~

**Comment by thibauts** [comment]
Not like that. You have to expose your file over HTTP and provide the URL to the module.

**Comment by iamdriz** [comment]
So I created a web server and the url was now: `http://localhost/~cameron/` as the base.

But I get the same error... Any ideas for this? Do I need to do something special to make it accessible outside? Perhaps replace the localhost with an ip address?

**Comment by thibauts** [comment]
The URL passed to `load` is sent to the Chromecast. Then the Chromecast tries to GET it. So yes, if you send `localhost` your chromecast will try to connect to itself. You have to find your local IP address (local network) and use it instead.

If you don't know how to do it, either look it up on google or check the `networkInterfaces` function of the node `os` module.

**Comment by iamdriz** [comment]
Okay so I setup apache I can access the file on my iPhone and iPad on the same WiFi with:

`http://cameron.local/~cameron/chromecast/example.mp4`

But when I try and use this as the contentId I get the load failed message... Any ideas?

**Comment by thibauts** [comment]
The server you use has to deliver the file with the right content-type, implement CORS and respond to range requests. Usually a simple express server with the static middleware will implement range requests and return the right conten-type, and you can add CORS quite easily with an added middleware. One such exemple is the peerflix server.

**Comment by iamdriz** [comment]
Why can I access the file using another computer, my iPad and my iPhone? But not the Chromecast? As if this was a CORS issue, then surely all those would be affected to?

**Comment by thibauts** [comment]
No of course not as those devices access your video file as an origin ... I gave you all the information you need to get a server working but you'll have to do the rest of the work yourself :)

Maybe start by looking up what CORS is and how it works.

**Comment by iamdriz** [comment]
Why would those devices access the file differently? I can access the file using a PC that hasn't had anything special done with it... What's Chromecast doing so differently?

**Comment by thibauts** [comment]
Please lookup what CORS is. I won't be able to explain it to you here.

**Comment by iamdriz** [comment]
I know what CORS is. I use it for APIs I have written in CakePHP. But I still don't understand why one device is fine and another not.

**Comment by thibauts** [comment]
Because one asks for CORS headers and the other doesn't.

**Comment by iamdriz** [comment]
Okay! Thanks, that's what I wanted to know.
