### ISSUE TITLE
Stop casting

### ISSUE THREAD

**Issue by seriousme** [thibauts/node-castv2-client#33]
Hi,

thanks for creating the client. 
I'm trying to show an image for an hour or so.
Showing the image works, but I can't get the cast to stop. If I disconnect the client the cast continues (as expected ;-))

It seems like I need a player.unload()
(see "The second movie I try to play -- doesn't" at  https://developers.google.com/cast/docs/player )

Any help would be appreciated.

Hans

**Comment by thibauts** [comment]
Hi. Have you tried `player.stop()' ?

If this doesn't work, you should have better luck by stopping the application altogether with something like : 

```javascript
client.stop(player, function(err, response) {
  //
});
```

**Comment by seriousme** [comment]
player.stop() did not work:
```
[Error: Invalid request: INVALID_MEDIA_SESSION_ID]
```
 as the media session seems to be stopped as soon as the image is shown.

```
client.stop(player, function(err, response) {
  //
});
```
Thx !
Now my next step is to use PhantomJS to generate the image :-)
