### ISSUE TITLE
'error' never emitted even though 'status' is emitted with idleReason ERROR

### ISSUE THREAD

**Issue by Ivshti** [thibauts/node-castv2-client#34]
Status event is emitted with idleReason equal to "ERROR" but no "error" event is emitted on the client for a detailed error report.

This could be an issue with chromecast, but I don't know. 

Is there a way to get a detailed error report of what is happening when playback stops due to an error?

Let me tell you about my use case: I have an HLS stream which works perfectly on the Apple stuff (iOS, airplay, QuickTime) but plays choppily on Chromecast for about 20-30 seconds before stopping playing with an error.

**Comment by Ivshti** [comment]
The cast2 protocol implementation seems to handle errors:
https://github.com/thibauts/node-castv2/blob/master/lib/channel.js
Although not fully, as the only one handled is unsupported protocol version.

But the "error" event cycle is broken in two places:
https://github.com/thibauts/node-castv2-client/blob/master/lib/controllers/controller.js - error is never passed on
https://github.com/thibauts/node-castv2/blob/master/lib/channel.js - error is never passed on

**Comment by thibauts** [comment]
Technically there is no error happening in the modules, in your case. So no error is raised or triggered. If the Chromecast is able to bubble back an error status, most likely it's an app failure.

I need more information to assess your problem. Could you please tell me which app you use (post a link to the source if relevant) and send a dump of the culprit status event ? Detailed information about how / when the bug happens would be helpful too.

**Comment by Ivshti** [comment]
The issue is not in the modules, but as I said, I am expecting chromecast to send some sort of error event which we can catch.
I ran with DEBUG=castv2,castv2-client,chromecasts, which logs all events received in the socket - there was no information besides status changing and giving an "IdleReason" "ERROR", so I think we can close this and rule it an issue in Chromecast.

Off topic, I believe the reason for the errors in non-monotonous DTS stamps, as when I use ffmpeg to convert the HLS stream, I get only these warnings - it couldn't really be anything else.
