### ISSUE TITLE
Set REPEAT_ON on DefaultMediaReceiver

### ISSUE THREAD

**Issue by Geminium** [thibauts/node-castv2-client#35]
Hello,

Many thanks for your library.
I'm using your example code for playing a video on my chromecast. It works very well.

I would like to know how to set repeat mode (REPEAT_ON / REPEAT_OFF) on video launch.

Can you help me please ?
Thanks

**Comment by thibauts** [comment]
Hi,

There doesn't seem to be provision for doing that in the protocol, from what I see in the [SDK documentation](https://developers.google.com/cast/docs/reference/messages).

As far as I recall, you'll receive a media status message/event when playback is done so you should be able to implement the repeat feature this way with a few lines of code.

Something along these lines :

```javascript
player.on('status', function(status) {
  if(player idle) {
    player.play(...);
  }
});

player.load(..., function(err, status) {
  player.play(...);
});
```

**Comment by jeffdagala** [comment]
Hi,

you could provide REPEAT_ALL if you want to repeat all of the items or REPEAT_SINGLE for the current item played.

You can also see the documentation here: https://developers.google.com/cast/docs/reference/receiver/cast.receiver.media#.repeatMode

**Comment by thibauts** [comment]
Thanks @jeffdagala :) Could you provide a short example, like by copy pasting the above code and adding the right media object structure ? That would solve the issue and probably help other people looking to achieve the same.

**Comment by jeffdagala** [comment]
So I've modified the load function to this:

```javascript
MediaController.prototype.load = function(media, options, callback) {

  if(typeof options === 'function' || typeof options === 'undefined') {
    callback = options;
    options = {};
  }

  var data = { type: 'LOAD' };

  data.autoplay = (typeof options.autoplay !== 'undefined')
    ? options.autoplay
    : false;

  data.currentTime = (typeof options.currentTime !== 'undefined')
    ? options.currentTime
    : 0;

  data.activeTrackIds = (typeof options.activeTrackIds !== 'undefined')
    ? options.activeTrackIds
    : [];

  data.repeatMode = (typeof options.repeatMode === "string" && 
    typeof options.repeatMode !== 'undefined')
    ? options.repeatMode
    : "REPEAT_OFF";
    
  data.media = media;

  this.request(data, function(err, response) {
    if(err) return callback(err);
    if(response.type === 'LOAD_FAILED') {
      return callback(new Error('Load failed'));
    }
    var status = response.status[0];
    callback(null, status);
  });
};
```
Example to pass repeatMode value:
```javascript
// ... is the media info
player.load(..., { autoplay: true, repeatMode: "REPEAT_ALL"}, function(err, status) {
    console.log('media loaded playerState=%s', status.playerState);
});
```

**Comment by thibauts** [comment]
Looks perfect. Would you make a PR for this feature ?

**Comment by thibauts** [comment]
Awesome thank you :)

**Comment by Geminium** [comment]
Hello, it does not work for me. value is REPEAT_ALL OR REPEAT_SINGLE.

**Comment by thibauts** [comment]
I guess it depends on what you want to achieve. [https://developers.google.com/cast/docs/reference/receiver/cast.receiver.media#.repeatMode](https://developers.google.com/cast/docs/reference/receiver/cast.receiver.media#.repeatMode)
