### ISSUE TITLE
specific launching multiple chromecasts / specific IP address

### ISSUE THREAD

**Issue by rossvz** [thibauts/node-castv2-client#36]
Having issues with running two chromecasts on the same network. I want to stream two different videos to each screen. With only one connected, things work fine because it's discovered automatically and its status is sent and received without issue. With two devices, i get this error message:
 
        node_modules/chromecast-js/node_modules/castv2-client/lib/controllers/receiver.js:50
        callback(null, response.status.applications || []);
                                                       ^
          TypeError: Cannot read property 'applications' of undefined

It seems that the status comes back undefined because the two chromecasts are interfering with each other or something. Is there a way to launch a new device/browser and specify the IP address manually?

**Comment by thibauts** [comment]
Of course, just call `client.connect()` with the chromecast's IP address like this : 

```javascript
client.connect('192.168.0.10', function() {
  //
});
```

**Comment by rossvz** [comment]
I did try that. And I get the content showing up on the screen, but it exits my app with this error:

       node_modules/castv2-client/lib/controllers/media.js:70
        var status = response.status[0];
                                   ^
         TypeError: Cannot read property '0' of undefined

Its something to do with trying to get the status from the chromecast that seems to be a problem?

**Comment by thibauts** [comment]
I just noticed you're using `chromecast-js`. I don't maintain it. Please post runnable code using `castv2-client` directly and I'll see what I can do. Thanks !
