### ISSUE TITLE
Casting a webpage

### ISSUE THREAD

**Issue by jeffdagala** [thibauts/node-castv2-client#40]
Is there a way to cast a website like http://www.google.com/ ?

**Comment by thibauts** [comment]
Not that I know of. This would make app validation difficult for google.

**Comment by jeffdagala** [comment]
Is there a way to create a custom receiver on this application? I want to try it and have a website to be cast.

**Comment by thibauts** [comment]
This module is made to build senders only, "clients". Though you can make a custom receiver and then build a custom sender with this module to drive the receiver.

**Comment by francoislaberge** [comment]
Create a custom receiver and iframe the site you want to see. You won't easily be able to navigate though unless you do the navigation from the outside page somehow.
