### ISSUE TITLE
Multiple Chromecast and One Sender

### ISSUE THREAD

**Issue by jeffdagala** [thibauts/node-castv2-client#41]
Is there a way to have a multiple chromecast then plays the same video at the same time? Like having them group then send the message to that group.

**Comment by thibauts** [comment]
The Chromecast itself doesn't implement this, nor does this module. Though you could probably implement it quite easily by discovering all the devices on your network and then calling load / play in a loop. The synchronization won't be perfect but it's as far as you will get IMO.

**Comment by jeffdagala** [comment]
I see, thank you for your quick response on this. Currently i'm looping the list of devices I had then send load / play command. there's a second gap between the devices, that's why I asked this question.

**Comment by thibauts** [comment]
You may get better synchronisation by calling `load` on all devices and waiting for all `load` calls to complete before calling `play` in a loop. This way your media will be preloaded and preloading time won't induce too much delay.

**Comment by jeffdagala** [comment]
Yes, that is what I did because if I load then play before the next device the gap would be 2 to 5 seconds.
