### ISSUE TITLE
Audio multicast

### ISSUE THREAD

**Issue by angelnu** [thibauts/node-castv2-client#45]
Thanks for your great library. I was able to successfully use it  in my [project](https://github.com/angelnu/ioBroker.chromecast).

Google has launched multi-cast support for audio devices. I tried to use chrome-cast but I did not manage to get it working.

I am able to connect and retrieve the client status but I do not know what to do next. I noticed that one device in the group becomes the MultizoneLeader while the others become MultizoneFollower:

* `{"applications":[{"appId":"MultizoneLeader","displayName":"Plex","sessionId":"92AE3423-8D88-4D97-BD6F-C94302C6E81F","statusText":"Plex"}],"volume":{"level":0.20000000298023224,"muted":false}}`
*  `{"applications":[{"appId":"MultizoneFollower","displayName":"Plex","namespaces":[{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"C80FDF67-4A60-42E9-B6A3-2A932D83D5F8","statusText":"Plex","transportId":"multizone-2"}],"volume":{"level":0.20000000298023224,"muted":false}}`

The transportId is the same in all the followers but I do not know why this is not included in the MultizoneLeader.

I can join the sesion for the MultizoneFollower but I never get status updates. Trying to connect to the MultizoneLeader fails an uncaught exception error.

Using MDNS or SSDP does not return the name of the group, only the individual devices.

Any ideas or documentation sources? Did you have to reverse-engineer the protocol with Whitesark?

**Comment by thibauts** [comment]
I have no idea...

If you want to RE the protocol Wireshark is useless as the connection is encrypted with TLS. You'll find insights about the protocol basics here https://github.com/thibauts/node-castv2#protocol-description, and a method to listen to the Chrome extension's traffic here https://github.com/vincentbernat/nodecastor#protocol-description. With this you should be able to sniff the connections and get a better understanding of the part of the protocol you're interested in pretty easily.

If you find something don't hesitate to send a PR :)

**Comment by angelnu** [comment]
Thanks thibauts,

my initial test found that the MDNS implementation in chromecast-scanner was filtering the groups: when I use avahi-discover I found that the audio groups are being returned **with a different port**.

When I connect to this port I am able to use it as a normal Chromecast device. So supporting audio groups might be not to difficult :-)

I have to continue playing with the chromecast-scanner source code so that I can return the groups as virtual chromecast. So far I manage to get the MDNS entry but this does not seem to contain the port...

**Comment by angelnu** [comment]
I used the code bellow to discover all devices, including audio groups. So there is no general issue with the castv2 library in order to use it for audio groups.

Do you want to include the instructions for audio groups in the readme or should I close this issue?
```
function mdsn_scan(callback){
    var m = mdns();
    
    var found_devices = [];

    var onResponse = function(response) {
        
        var txt_field = find(response.additionals, function(entry) {
            return entry.type === 'TXT';
        });

        var srv_field = find(response.additionals, function(entry) {
            return entry.type === 'SRV';
        });

        var a_field = find(response.additionals, function(entry) {
            return entry.type === 'A';
        });

        if (!txt_field || !srv_field || !a_field) {
            return;
        }
        
        //console.log('txt:\n', util.inspect(txt.decode(txt_field.data)));
        
        var ip   = a_field.data;
        var name = txt.decode(txt_field.data).fn;
        var port = srv_field.data.port;
        
        
        if (!ip || !name || !port) {
            return;
        }
        
        if (found_devices.indexOf(name) < 0){
            found_devices.push(name);
            callback(ip, name, port);            
        }
        
        
    }
    m.on('response', onResponse);

    m.query({
      questions:[{
        name: '_googlecast._tcp.local',
        type: 'PTR'
      }]
    });
}
```

**Comment by thibauts** [comment]
Hello :) I think this would fit well in the wiki. You could also mention it in the main README. What do you think ?

**Comment by angelnu** [comment]
Ok, then I will work on a pull request proposal for the readme update.

Would you like to have the scanner code in the library? I could clean it a little bit and add it to the library.

**Comment by thibauts** [comment]
No I'd prefer not to include any scanner code as the scope of the module doesn't include discovery. That being said, definitely put it in the wiki so it's not lost. It may be later included in a separate discovery module.

**Comment by angelnu** [comment]
[Done](https://github.com/thibauts/node-castv2-client/wiki/How-to-discover-update-audio-groups)

Since you mention another module: I found [chromecast-scanner](https://github.com/xat/chromecast-scanner). Should the scanner code be contributed there?

**Comment by thibauts** [comment]
Looks like a good idea :)

**Comment by angelnu** [comment]
And they had already a nice [issue](https://github.com/xat/chromecast-scanner/issues/4) waiting :-D
