### ISSUE TITLE
Error Streaming to Chromecast Audio Group

### ISSUE THREAD

**Issue by nguyer** [thibauts/node-castv2-client#48]
Hi there,

Thanks for this great module! Using the sample provided in the README.md I have a working app streaming to one Chromecast Audio at a time. I also have these same devices in a Cast Group. I can find each device and the group:

```
found device "Living Room" at 192.168.1.111:8009
found device "Basement" at 192.168.1.139:8009
found device "All Speakers(1)" at 192.168.1.139:38143
```
(I have no idea why it's adding the `(1)` to the end of my group. Separate question I guess.)

However, if I try to play to that group, it seems to almost work, and then it fails:
```
connected, launching app ...
app "Default Media Receiver" launched, loading media http://192.168.1.115:3000/All_Speakers(1).mp3 ...
[Error: Load failed]
```

Do you have any idea why it is failing to load? Is there something different I have to do on a group? Does the fact that it's using a different port have anything to do with it?

I have also confirmed that I never get an HTTP request to the media URL that it's trying to load. It looks like it never makes it that far. Any help you could offer would be great!

Thanks!

**Comment by thibauts** [comment]
Hello. Could you run your script prefixed in debug mode and post the log ?

```bash
DEBUG=* node yourscript.js
```

**Comment by nguyer** [comment]
Sure! Here's the log.
[log.txt](https://github.com/thibauts/node-castv2-client/files/111513/log.txt)

I also noticed that I hear the connect sound on one of the Chromecast audios, but not the other one. Not sure if that helps.

**Comment by nguyer** [comment]
Hmm...I discovered if I remove the `(1)` from the path that makes the `[Error: Load failed]` go away :) I guess something didn't like those parentheses. Maybe because that was part of the media URL that I was telling it to request.

But it's still only working with one Chromecast. Is there something else I need to do to get audio out of both?

**Comment by thibauts** [comment]
Well, the log doesn't bring in much information. Looks like all we'll know from the group Chromecast is that the LOAD command fails. I don't know anything about groups by the way. Are you positive playing on groups with the default media receiver is possible ? If it is, you may want to find a regular sender that demonstrates it and sniff traffic to learn what's needed exactly to get it to work.

You'll find instructions [here](https://github.com/vincentbernat/nodecastor#protocol-description).

**Comment by nguyer** [comment]
Okay. Maybe I'll have to dig into it more. I thought I read in another issue that groups worked but maybe that was just for discovery. I'm not really sure how the default media receiver works yet. Thanks for your help!
