### ISSUE TITLE
Multiple audio tracks for video stream?

### ISSUE THREAD

**Issue by z-ax** [thibauts/node-castv2-client#49]
Greetings! Is it possible to work with multiple audio tracks of video stream (provided via URL)? Switch between them during video playback.

Will appreciate any help in this direction.

**Comment by thibauts** [comment]
As far as I know it's not possible. But Chromecast 2 may have brought this kind of capability on the table. You'll get a definitive answer by looking into the official SDK. If they have this kind of feature we most probably can implement it.

It would be awesome if you can add the feature to the module :)

**Comment by z-ax** [comment]
I was playing with Electron recently, and decided to make a nice Chromecast app with GUI as far as it's pretty fast now and didn't find any ready-to-use apps, with sending direct links and playlists :)

Your lib is pretty helpful for me. Hopefully, will have time next week to check the SDK, but now very busy with projects.

Thanks for reply!
