### ISSUE TITLE
volume control

### ISSUE THREAD

**Issue by beckmx** [thibauts/node-castv2-client#50]
Hello guys, does anybody know or has any idea on how to set the volume up?

**Comment by Ivshti** [comment]
See this: https://github.com/mafintosh/chromecasts/blob/master/index.js#L207-L217
`player` is a castv2 client

**Comment by jonferreira** [comment]
I'd like to know this and TBH the above link didn't helped me at all :-(

**Comment by jonferreira** [comment]
```
client.setVolume({ level: 0.5 }, function(err, newvol){
		if(err) console.log("there was an error setting the volume")
		console.log("volume changed to %s", newvol)
	});
```

finally found it!
