### ISSUE TITLE
Audio never loads

### ISSUE THREAD

**Issue by facekapow** [thibauts/node-castv2-client#51]
I'm trying to add Chromecast support to my [Electron app](http://github.com/facekapow/hypertunes) and I stumbled upon a bug. What I do is I setup a temporary server when the user requests to cast and serve the audio they want (I know this part is fine because I setup the server and created a mini test file for Chrome with the regular Cast extension and it casted the audio fine). The problem is that when using `node-castv2-client`, the audio never stops buffering. A little bit after the initial load request, I get a status update saying that the audio has been paused, but the Chromecast just keeps buffering. I even made sure to add `audio/mpeg` as the `contentType`, but nothing.

**Comment by thibauts** [comment]
I never tried to stream pure audio but I guess it should work fine.

Can you provide a log of what happens on the server side ?

**Comment by facekapow** [comment]
Sure:

```
server started.
server request: /stream
currently set audio path: /Users/me/Music/test_song.mp3
mime type: audio/mpeg
file size: 8910376
request piped
server request: /stream
currently set audio path: /Users/me/Music/second_song.mp3
mime type: audio/mpeg
file size: 251020
request piped
```

**Comment by facekapow** [comment]
Wow, I feel really stupid. Sorry about this. All that was wrong was that I forgot to set `autoplay: true`. Thanks for the quick response, and again, sorry.

**Comment by thibauts** [comment]
No problem. Did you have to respond to range requests or only piping your file to the response stream did the trick ?

**Comment by facekapow** [comment]
I had to add `Transfer-Encoding: chunked` and `Accept-Ranges: bytes` to get it to stream, other than that it was just an `fs.createReadStream(pathname).pipe(res)`.

**Comment by thibauts** [comment]
If my memory serves me well, range-parser dans createReadStream options played well together if you need seeking abilities. Anyway have fun with your app !
