### ISSUE TITLE
Security: Regular Expression Denial of Service

### ISSUE THREAD

**Issue by feross** [thibauts/node-castv2-client#52]
See https://nodesecurity.io/advisories/46

Caused by:

castv2-client@1.1.1 > debug@1.0.4 > ms@0.6.2

You need to use the latest version of debug, which pulls in `ms` version 0.7.1 or greater.

**Comment by thibauts** [comment]
Done. Thanks for the heads up !

**Comment by feross** [comment]
No problem!
