### ISSUE TITLE
Set the user-agent?

### ISSUE THREAD

**Issue by johnspurlock** [thibauts/node-castv2-client#54]
Hi there, is it possible to provide the userAgent string sent over to the receiver?  i.e. the one that ends up in [onSenderConnected](https://developers.google.com/cast/docs/reference/receiver/cast.receiver.CastReceiverManager.SenderConnectedEvent).

Right now it is the empty string.

Thanks!

**Comment by thibauts** [comment]
Hi John, I don't know how the user-agent is transmitted. I have not observed it in the protocol when I worked on it. This is probably something new and I have no clue !

**Comment by johnspurlock** [comment]
Ok - any pointers on where to look?  I tried searching for "agent" in various github repos that try and implement the v2 protocol, no luck.

I imagine it's probably in the chromium source somewhere, do you remember where you were looking for hints like this?

**Comment by thibauts** [comment]
Most castv2 implementations (if not all) are based on this implementation.

You'll find instructions [here](https://github.com/vincentbernat/nodecastor#protocol-description) for protocol snooping.
