### ISSUE TITLE
Add scanner?

### ISSUE THREAD

**Issue by angelnu** [thibauts/node-castv2-client#66]
Hi,

should I propose a pull request to add an scanner for chromecast devices?

I was thinking in something similar to the scanner in my [iobroker project](https://github.com/angelnu/ioBroker.chromecast/blob/master/lib/chromecastScanner.js#L40). I took a subset as well for #65 .

**Comment by thibauts** [comment]
As discussed in previous issues, i'd prefer to leave it to other modules. A
simple example in the readme could do the trick, imo.

**Comment by angelnu** [comment]
Ok, then we can close this.

I am thinking in splitting the base functions in my project such as scanning and media queries to an extra module.

**Comment by thibauts** [comment]
There is [this module](https://github.com/xat/chromecast-scanner) for scanning. It has been developed by someone who has good understanding of the chromecast ecosystem. Could you use it in your examples ? Reflecting this in the README would be perfect, too. But I'll do it when I have some free time if you can't.

**Comment by angelnu** [comment]
For the base examples the chromecast-scanner would work but it has some limitations to be aware of:

- it does not include the Chromecast name - service.name is an UID
- it does not return the port - audio groups use random ports
- it does not re-issue the query

I will see if I can prepare a pull request to add these capabilities to the chromecast-scanner so that I do not need my own fork.

**Comment by thibauts** [comment]
Would be nice to update the scanner module or publish another clean one which handles multiple devices cleanly.

**Comment by angelnu** [comment]
I have cloned the module and will work on the changes later. Then I will ask @xat if he want the changes or if he prefers a new module.

Currently I am working in a a player that makes easier to work with the playlist. Ideally it will accept a pls or m3u file, covert it to a chromecast list and start playing it.

I will also add support for announcements so that I can play URL in a playing device and then resume the original playlist. I need this to support playing a text such as forecast test to devices playing my music. (More details [here](https://github.com/ioBroker/ioBroker.sayit))

**Comment by thibauts** [comment]
Do as you like, as long as the examples and README use a simple scanner without including its code in thie module it's fine with me :)

**Comment by angelnu** [comment]
Fyi: I ended up splitting the code from my previous project and creating and stand alone player that is able to handle playlists, re-connects/retries, announcements, retrieving metadata via ICY, etc.

https://github.com/angelnu/castv2-player
