### ISSUE TITLE
Cast from Google Music?

### ISSUE THREAD

**Issue by ovsleep** [thibauts/node-castv2-client#67]
Is it possible to cast a playlist from google music? or spotify?
Haven't found anything like this in any other library, so not sure if it's even posible

**Comment by thibauts** [comment]
If no official app can do it, chances are it's not possible :)

**Comment by germasch** [comment]
The google music app and webpage let you cast, so it's possible, there's a receiver app. Once playing, it can be controlled with the MediaController in castv2-client. I don't seem to be able to snoop the websocket traffic on my Chrome, but I guess there's going to be some kind of access tokens involved anyway, which would probably prevent load a playlist without an official app involved.
