### ISSUE TITLE
Security Vulnerability - protobufjs

### ISSUE THREAD

**Issue by jaxcore** [thibauts/node-castv2-client#91]
This package relies on castv2 which isn't maintained anymore and has a dependency vulnerability that is showing in NPM.

https://github.com/thibauts/node-castv2/issues/54

I suggest forking that project and updating protobufjs to 5.0.3 or later.

**Comment by Hypnos3** [comment]
This project is maintained by the same person as node-castv2.

Google itself encourage to no longer use the cast v2 protokoll and migrate to the new Cast Application Framework (CAF).

**Comment by jaxcore** [comment]
Oh whoops, not sure what should be done then. This library is still in wide use, and does still work at least for now, aside from that protobufjs dependency.

**Comment by thibauts** [comment]
I'm a bit busy right now but will be able to address various issues in a few weeks.

**Comment by feross** [comment]
Hi everyone, I have a pull request that fixes this issue but I don't have a Chromecast handy at the moment to test it out. Can someone confirm that the code in this pull request still works correctly?

https://github.com/thibauts/node-castv2/pull/56

**Comment by feross** [comment]
Fixed in `castv2@0.1.10`.
